### ISSUE TITLE
Number of persons not shown correctly

### ISSUE THREAD

**Issue by GerDijkstra** [HuygensING/timbuctoo#144]
Uploaded a test file that contains 17441 individual persons. Timbuctoo says "found 9400 persons", with no filters set. Then the number of males (8707) plus females (689) leads to another, different number.

![screen shot 2017-02-01 at 14 42 19](https://cloud.githubusercontent.com/assets/25342506/22509174/2dd48fa6-e88d-11e6-85c9-fced71a6edca.jpg)

#### Expected/Desired behaviour

Show all 17441 persons

#### Actual behaviour

Only 9400 persons found

#### Extra info
N/A

**Comment by jauco** [comment]
Most of the difference was due to the indexing job breaking off halfway through. We fixed this by (a) throwing away all indices when a job breaks off (making it clear that the indexing job failed) and (b) making it more resilient to failed http requests

What's left over is: 
- [ ] some relations point to Person_name_variants instead of Persons however, so that might also have an effect on the amount of persons.
- [ ] Some persons are indexed as neither male, nor female

**Comment by jauco** [comment]
I have 17442 person-records in the excel (not 17441) so the number in the current import matches.

The number of males/females is still of by 6, but that is due to 6 persons having no gender information in the excel file

<img width="936" alt="screen shot 2017-02-07 at 12 40 39" src="https://cloud.githubusercontent.com/assets/68318/22689799/e50f3a5a-ed32-11e6-9dcc-f626c5c26dbb.png">

Moving the fact that some relations are incorrect to a new issue
