### ISSUE TITLE
[T125] upload nieuwe data 2TBI

### ISSUE THREAD

**Issue by marnixvb** [HuygensING/timbuctoo#253]

**Comment by pjoshi04** [comment]
I found a little issue in the 2TBI data changefiles when trying to import it using resourcesync. Few of the changefiles have the following at the end of the file so Timbuctoo has problems parsing it:

>  \ No newline at end of file

I found out that this happens if you don't sort the original files and directly create a diff. [The Resourcesync exchange protocol doc](https://github.com/HuygensING/timbuctoo/blob/master/documentation/exchange-protocol.adoc) states sorting as a step for generating the diff files.

**Comment by MMaas3** [comment]
Update succeeded yesterday

**Comment by MMaas3** [comment]
Looks like it still got an issue
