### ISSUE TITLE
T134: 2TBI - check validity of changelist

### ISSUE THREAD

**Issue by marnixvb** [HuygensING/timbuctoo#268]

**Comment by pjoshi04** [comment]
The changelist is valid according to the general [resourcesynce specifications](http://www.openarchives.org/rs/1.1/resourcesync#DesChanges) but doesn't meet the stricter definition for patching that we have in Timbuctoo for our [exchange protocol](https://github.com/HuygensING/timbuctoo/blob/2e40a02ad534e38d25460cd9039bb27a9f7872d6/documentation/exchange-protocol.adoc)

Namely, we specify that we need every single change to the dataset to be present in the nqud files present in the changelist patch.

**Comment by pjoshi04** [comment]
Re-opening because I want to test in production servers as well.

**Comment by pjoshi04** [comment]
Re-opening as Lodewijk received a response from the 2TBI people. Seems the data they uploaded is in a seperate dataset/seperate resource sync link. Will investigate.

**Comment by pjoshi04** [comment]
Tried uploading the 2TBI dataset.nq to a local instance of Timbuctoo (using RDF upload endpoint) and Timbuctoo complained about few unexcaped characters in the dataset. Example:

> `"[\01,cr\]Строение вселенной"`

(Manually) replaced them as follows:

> `"[\\01,cr\\]Строение вселенной"`

Will have to upload the dataset to Anansi so that Lodewijk can take a better look at it and see if everything he expects is present.

**Comment by pjoshi04** [comment]
Uploaded _dataset.nq_ from the new TIC2 resourcelist to Anansi (dataset: u0b4a3b0677e8bed3acb26c2d785a1b2090b59bbb__tic2)
